apiVersion: apps/v1
kind: Deployment
metadata:
  name: asrllm-admin-web
  namespace: asrllm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asrllm-admin-web
  template:
    metadata:
      labels:
        app: asrllm-admin-web
    spec:
      containers:
        - name: admin-web
          image: asrllm/admin-web:0.1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: asrllm-admin-web
  namespace: asrllm
spec:
  selector:
    app: asrllm-admin-web
  ports:
    - port: 80
      targetPort: 80
